// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {main} from '../models';
import {hottrend} from '../models';
import {tools} from '../models';
import {mcp} from '../models';

export function AddAgentConfig(arg1:models.AgentConfig):Promise<string>;

export function AddMCPServer(arg1:models.MCPServerConfig):Promise<string>;

export function AddStrategy(arg1:models.Strategy):Promise<string>;

export function AddToWatchlist(arg1:models.Stock):Promise<string>;

export function CancelInterruptedMeeting(arg1:string):Promise<boolean>;

export function CancelMeeting(arg1:string):Promise<boolean>;

export function CaptureReviewScreen():Promise<models.ReviewScreenCaptureResult>;

export function CheckForUpdate():Promise<services.UpdateInfo>;

export function ClearSessionMessages(arg1:string):Promise<string>;

export function CompareReviewArticles(arg1:models.CompareReviewRequest):Promise<models.CompareReviewResult>;

export function CreateDailyReview(arg1:models.CreateDailyReviewRequest):Promise<models.ReviewArticleDetail>;

export function DeleteAgentConfig(arg1:string):Promise<string>;

export function DeleteMCPServer(arg1:string):Promise<string>;

export function DeleteReviewArticle(arg1:string):Promise<string>;

export function DeleteReviewTemplate(arg1:string):Promise<string>;

export function DeleteStrategy(arg1:string):Promise<string>;

export function DoUpdate():Promise<string>;

export function DownloadReviewImage(arg1:models.DownloadReviewImageRequest):Promise<models.SaveReviewImageResult>;

export function EnhancePrompt(arg1:main.EnhancePromptRequest):Promise<main.EnhancePromptResponse>;

export function GenerateStrategy(arg1:main.GenerateStrategyRequest):Promise<main.GenerateStrategyResponse>;

export function GetActiveStrategyID():Promise<string>;

export function GetAgentConfigs():Promise<Array<models.AgentConfig>>;

export function GetAllHotTrends():Promise<Array<hottrend.HotTrendResult>>;

export function GetAvailableTools():Promise<Array<tools.ToolInfo>>;

export function GetBoardFundFlow(arg1:string,arg2:number,arg3:number):Promise<models.BoardFundFlowList>;

export function GetBoardLeaders(arg1:string,arg2:number):Promise<models.BoardLeaderList>;

export function GetConfig():Promise<models.AppConfig>;

export function GetCurrentVersion():Promise<string>;

export function GetF10Overview(arg1:string):Promise<models.F10Overview>;

export function GetF10Valuation(arg1:string):Promise<models.StockValuation>;

export function GetHotTrend(arg1:string):Promise<hottrend.HotTrendResult>;

export function GetHotTrendPlatforms():Promise<Array<hottrend.PlatformInfo>>;

export function GetKLineData(arg1:string,arg2:string,arg3:number):Promise<Array<models.KLineData>>;

export function GetLongHuBangDetail(arg1:string,arg2:string):Promise<Array<models.LongHuBangDetail>>;

export function GetLongHuBangList(arg1:number,arg2:number,arg3:string):Promise<services.LongHuBangListResult>;

export function GetMCPServerTools(arg1:string):Promise<Array<mcp.ToolInfo>>;

export function GetMCPServers():Promise<Array<models.MCPServerConfig>>;

export function GetMCPStatus():Promise<Array<mcp.ServerStatus>>;

export function GetMarketIndices():Promise<Array<models.MarketIndex>>;

export function GetMarketStatus():Promise<services.MarketStatus>;

export function GetOpenClawStatus():Promise<Record<string, any>>;

export function GetOrCreateSession(arg1:string,arg2:string):Promise<models.StockSession>;

export function GetOrderBook(arg1:string):Promise<models.OrderBook>;

export function GetReviewArticle(arg1:string):Promise<models.ReviewArticleDetail>;

export function GetReviewArticles(arg1:models.ReviewListRequest):Promise<models.ReviewListResult>;

export function GetReviewAssetBase64(arg1:string):Promise<string>;

export function GetReviewSummaryArticle():Promise<models.ReviewArticleDetail>;

export function GetReviewTemplates():Promise<Array<models.ReviewTemplate>>;

export function GetSessionMessages(arg1:string):Promise<Array<models.ChatMessage>>;

export function GetStockMoves(arg1:string,arg2:number,arg3:number):Promise<models.StockMoveList>;

export function GetStockRealTimeData(arg1:Array<string>):Promise<Array<models.Stock>>;

export function GetStrategies():Promise<Array<models.Strategy>>;

export function GetTelegraphList():Promise<Array<services.Telegraph>>;

export function GetTradeDates(arg1:number):Promise<Array<string>>;

export function GetTradingSchedule():Promise<services.TradingSchedule>;

export function GetWatchlist():Promise<Array<models.Stock>>;

export function Greet(arg1:string):Promise<string>;

export function NotifyFrontendReady():Promise<void>;

export function OCRReviewImage(arg1:models.ReviewOCRRequest):Promise<models.ReviewOCRResult>;

export function OpenURL(arg1:string):Promise<void>;

export function RebuildReviewIndex():Promise<string>;

export function RemoveFromWatchlist(arg1:string):Promise<string>;

export function RestartApp():Promise<string>;

export function RetryAgent(arg1:string,arg2:string,arg3:string):Promise<models.ChatMessage>;

export function RetryAgentAndContinue(arg1:string):Promise<Array<models.ChatMessage>>;

export function SaveReviewArticle(arg1:models.SaveReviewArticleRequest):Promise<models.ReviewArticleDetail>;

export function SaveReviewPastedImage(arg1:models.SaveReviewImageRequest):Promise<models.SaveReviewImageResult>;

export function SaveReviewTemplate(arg1:models.SaveReviewTemplateRequest):Promise<models.ReviewTemplate>;

export function SearchStocks(arg1:string):Promise<Array<services.StockSearchResult>>;

export function SendMeetingMessage(arg1:main.MeetingMessageRequest):Promise<Array<models.ChatMessage>>;

export function SetActiveStrategy(arg1:string):Promise<string>;

export function TestAIConnection(arg1:models.AIConfig):Promise<string>;

export function TestMCPConnection(arg1:string):Promise<mcp.ServerStatus>;

export function UpdateAgentConfig(arg1:models.AgentConfig):Promise<string>;

export function UpdateConfig(arg1:models.AppConfig):Promise<string>;

export function UpdateMCPServer(arg1:models.MCPServerConfig):Promise<string>;

export function UpdateStockPosition(arg1:string,arg2:number,arg3:number):Promise<string>;

export function UpdateStrategy(arg1:models.Strategy):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
